---
apiVersion: v1
kind: Pod
metadata:
  name: core-envoy
spec:
  containers:
    - image: envoyproxy/envoy:v1.22.0
      name: envoy
      volumeMounts:
      - name: config
        mountPath: "/etc/envoy"
        readOnly: true
      ports:
      - name: core-envoy-port
        containerPort: 8080
  volumes:
    - name: config
      configMap:
        name: core-envoy-config