---
apiVersion: v1
kind: Pod
metadata:
  name: core
spec:
  containers:
    - image: ghcr.io/sailgame/core:v1.5.0
      name: core
      ports:
      - name: core-port
        containerPort: 8080

  imagePullSecrets:
    - name: dockerconfigjson-github-com